/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportadoraRouteImport } from './routes/transportadora'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'

const TransportadoraRoute = TransportadoraRouteImport.update({
  id: '/transportadora',
  path: '/transportadora',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/transportadora': typeof TransportadoraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/transportadora': typeof TransportadoraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/transportadora': typeof TransportadoraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cliente' | '/importar' | '/login' | '/transportadora'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cliente' | '/importar' | '/login' | '/transportadora'
  id: '__root__' | '/' | '/cliente' | '/importar' | '/login' | '/transportadora'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  TransportadoraRoute: typeof TransportadoraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportadora': {
      id: '/transportadora'
      path: '/transportadora'
      fullPath: '/transportadora'
      preLoaderRoute: typeof TransportadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  TransportadoraRoute: TransportadoraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
