// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://myhqxwviataxbydhgzmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aHF4d3ZpYXRheGJ5ZGhnem1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNTkwNTQsImV4cCI6MjA3ODczNTA1NH0.FekNqAw9EQ3g6gz2Hz-GzzkLktrw0-LjN9RRBfe-UsU";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);