// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bauarbmtzxtcktjpdmnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdWFyYm10enh0Y2t0anBkbW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5OTg1MDYsImV4cCI6MjA5MTU3NDUwNn0.zlgjC74Td_U1o42IY87OKBqfVis1f9jRnTpkNQhl6MI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);